# Generated by Django 5.2.6 on 2025-09-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='benefit_claims/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('employee_benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='benefits.employeebenefit')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='benefits.employeebenefit')),
            ],
        ),
    ]
