# Generated by Django 5.2.6 on 2025-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('PROBATIONARY', 'Probationary'), ('CONTRACTUAL', 'Contractual'), ('PROJECT_BASED', 'Project-based'), ('INTERN', 'Intern/Trainee'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned'), ('ON_LEAVE', 'On leave')], default='FULL_TIME', max_length=32),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phic_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='present_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sss_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenure_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tin_no',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
